--문제 1 전지연 사원이 속해 있는 부서원들을 제외 (전지연 제외)
--사번 / 사원명 / 전화번호 / 고용일 /부서명 
SELECT EMP_ID , EMP_NAME , PHONE ,TO_CHAR(HIRE_DATE,'YYYY/MM/DD')입사일,DEPT_TITLE
FROM EMPLOYEE
JOIN DEPARTMENT ON(DEPT_CODE = DEPT_ID)
WHERE DEPT_CODE = (SELECT DEPT_CODE
FROM EMPLOYEE
WHERE EMP_NAME = '전지연') AND
EMP_NAME != '전지연';



--문제 2 고용일이 2000년도 이후인 사람들 중 급여가 가장 높은 사원
SELECT MAX(SALARY)
FROM EMPLOYEE
WHERE EXTRACT(YEAR FROM HIRE_DATE) >2000;


SELECT EMP_ID,EMP_NAME,PHONE,SALARY,JOB_NAME
FROM EMPLOYEE
JOIN JOB USING(JOB_CODE)
WHERE SALARY = (SELECT MAX(SALARY)
                FROM EMPLOYEE
                WHERE EXTRACT(YEAR FROM HIRE_DATE) >2000);



--문제 3번 노옹철 사원과 같은 부서 직급인 사원 구하기
SELECT DEPT_CODE,JOB_NAME
FROM EMPLOYEE
JOIN JOB USING(JOB_CODE)
WHERE EMP_NAME = '노옹철';


SELECT EMP_ID,EMP_NAME,PHONE,SALARY,JOB_NAME
FROM EMPLOYEE
JOIN JOB USING(JOB_CODE)
WHERE (DEPT_CODE,JOB_NAME) = (
    SELECT DEPT_CODE,JOB_NAME
    FROM EMPLOYEE
    JOIN JOB USING(JOB_CODE)
    WHERE EMP_NAME = '노옹철'
)
AND EMP_NAME !='노옹철';



--문제 4 2000년도에 입사한 사원과 부서와 직급이 같은 사원 조회

SELECT EMP_NAME,HIRE_DATE
FROM EMPLOYEE
WHERE EXTRACT(YEAR FROM HIRE_DATE) = 2000;

SELECT EMP_ID,EMP_NAME,DEPT_CODE,JOB_CODE,TO_CHAR(HIRE_DATE,'YYYY/MM/DD')
FROM EMPLOYEE
WHERE (DEPT_CODE,JOB_CODE)=(SELECT DEPT_CODE,JOB_CODE
                            FROM EMPLOYEE
                            WHERE EXTRACT(YEAR FROM HIRE_DATE) = 2000);
                            
                            
--문제 5 77년생 여자 사원과 동일한 부서이면서 동일한 사수인 사람

SELECT DEPT_CODE,MANAGER_ID
FROM EMPLOYEE
WHERE SUBSTR(EMP_NO,1,2)='77' AND SUBSTR(EMP_NO,8,1)='2';

SELECT EMP_ID,EMP_NAME,DEPT_CODE,MANAGER_ID,EMP_NO,TO_CHAR(HIRE_DATE,'YYYY/MM/DD')
FROM EMPLOYEE
WHERE (DEPT_CODE,MANAGER_ID) = (
    SELECT DEPT_CODE,MANAGER_ID
    FROM EMPLOYEE
    WHERE SUBSTR(EMP_NO,1,2)='77' AND SUBSTR(EMP_NO,8,1)='2');
    


--문제 6 부서별 입사일 빠른 순서 
SELECT NVL(DEPT_CODE,'소속없음'),MIN(TO_CHAR(HIRE_DATE,'YYYY/MM/DD'))
FROM EMPLOYEE
GROUP BY EMP_ID,DEPT_CODE
ORDER BY 2;

SELECT EMP_ID,EMP_NAME,NVL(DEPT_TITLE,'소속없음'),JOB_NAME,TO_CHAR(HIRE_DATE,'YYYY/MM/DD')입사일,DEPT_CODE
FROM EMPLOYEE E1
LEFT JOIN DEPARTMENT ON(E1.DEPT_CODE = DEPT_ID)
JOIN JOB J ON(E1.JOB_CODE = J.JOB_CODE)
WHERE HIRE_DATE = (

        SELECT MIN(HIRE_DATE)
        FROM EMPLOYEE E2
        WHERE E2.DEPT_CODE = E1.DEPT_CODE
        OR (E2.DEPT_CODE IS NULL AND E1.DEPT_CODE IS NULL)
        AND ENT_YN !='Y')

ORDER BY HIRE_DATE;


--문제7번 직급별로 나이가 가장 어린 직원 조회 나이순 정렬

SELECT
    EMP_ID, EMP_NAME,JOB_NAME,
    EXTRACT(YEAR FROM sysdate) - ( '19'|| SUBSTR(emp_no, 1, 2) ) 나이,
   TO_CHAR((SALARY*12)*(1+NVL(BONUS,0)),'L9,999,900,000') "보너스 포함 연봉"
FROM
     EMPLOYEE E1
     JOIN JOB J ON(E1.JOB_CODE=J.JOB_CODE)
WHERE
    SUBSTR(emp_no, 1, 2) = (
        SELECT MAX(SUBSTR(emp_no, 1, 2))
        FROM  EMPLOYEE E2
        WHERE E2.JOB_CODE = E1.JOB_CODE  )
ORDER BY 나이 DESC;

select * from nls_session_parameters;

SELECT
TO_CHAR(((SALARY*12)*NVL2(BONUS,BONUS+1,1)),'9,999,900,000L')
FROM EMPLOYEE;