
SELECT USERNAME FROM DBA_USERS;

ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;

CREATE USER khg IDENTIFIED BY khg1234;
GRANT CONNECT, RESOURCE TO khg;
ALTER USER khg DEFAULT TABLESPACE SYSTEM QUOTA UNLIMITED ON SYSTEM;
